# 로컬 유레카 환경
server:
  port: 10232

eureka:
  client:
    registry-fetch-interval-seconds: 5  # default is 30
    fetch-registry: true # Eureka에서 다른 서비스 정보를 받아올지 여부
    register-with-eureka: true # 현재 애플리케이션을 Eureka에 등록할지 여부
    service-url:
      defaultZone: http://admin:1234@localhost:10230/eureka # 로컬 Eureka 서버의 주소
  instance:
    prefer-ip-address: true # 서비스 등록 시 도메인 대신 IP 주소로 등록

auth:
  jwt:
    create:
      url:
        http://localhost:10232/api/auth