# 공통 설정
spring:
  application:
    name: GATEWAY

  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:10240 # config 서버 연결

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*" # Actuator 의 모든 엔드포인트를 웹에서 노출 (운영환경에선 최소화 필요)
