# 공통 설정
spring:
  application:
    name: GATEWAY

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace # SQL 파라미터 바인딩 로그를 trace 레벨로 출력
    org.springframework.transaction.interceptor: trace # 트랜잭션 처리 로그를 trace 로 출력

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: "*" # Actuator 의 모든 엔드포인트를 웹에서 노출 (운영환경에선 최소화 필요)